name: Download Process
on:
  gollum
jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3.0.0
      with: 
        node-version: v16.14.2
    - name: Prepare your file
      run: |
        git clone "https://github.com/${GITHUB_REPOSITORY}.wiki.git"
        wiki=`echo $echo $GITHUB_REPOSITORY | cut -d "/" -f 2`.wiki
        cd "$wiki"
        drive=`git log --pretty=format: -1 --name-only *.md`
        export drive
        cd ..
        # wget `cat $wiki/$drive | xargs` --directory-prefix=download
        # npm i
        # npm start

        url=$(cat $wiki/$drive)
        name=${drive%.md}
        mkdir download
        cd download
        pwd
        echo $url
        echo $name
        # curl -Lo "" "https://download.cpming3.workers.dev/nda_1?url=KnbU=90U8=QMfFGZuZkMlMUNlQWYvxmb39GZfRXbfFmdhpmRyUyckF2bs52dvRmRyUSbvNmL1sGZq5iMzVnRyUiRyUSQzUCc0RHa"
        # curl --user "394912998@qq.com:aj4qt8htr95ccazh" -T nda_1 "https://dav.jianguoyun.com/dav/test/"
      env: 
        url: ${{ secrets.url }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        nutstore_url: ${{ secrets.nutstore_url }}
        nutstore_username: ${{ secrets.nutstore_username }}
        nutstore_password: ${{ secrets.nutstore_password }}
        box_url: ${{ secrets.box_url }}
        box_username: ${{ secrets.box_username }}
        box_password: ${{ secrets.box_password }}
        yandex_url: ${{ secrets.yandex_url }}
        yandex_username: ${{ secrets.yandex_username }}
        yandex_password: ${{ secrets.yandex_password }}

